---
name: Clean-up stale merged branches

on:
  schedule:
    - cron: 0 18 * * SUN
  workflow_dispatch:

jobs:
  clean-up-branches:
    name: Remove branches already merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch entire history
      - name: Find and remove branches already merged
        shell: bash
        run: |
          MAIN_BRANCH=main
          if [ `git branch --merged ${MAIN_BRANCH} | wc -l` == 1 ];
          then
            echo No merged branches found.
          else
            git branch --merged ${MAIN_BRANCH} | egrep -v "(^\*|${MAIN_BRANCH})" | xargs git push -d origin
            echo Removed all branches already merged.
          fi
        if: false
  clean-up-auto-updates:
    name: Remove pending auto-update branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch entire history
      - name: Find stale auto-update branches
        shell: bash
        run: |
          git branch --remotes | grep "auto-update/dependencies" | sed 's@origin/@@g' | head -n-1 | xargs git push -n -d origin
          echo Remove all pending auto-update branches, but the last
